# Site settings
title: "POST-AND-GET"
url: "//post-and-get.github.io"
highlighter: pygments
paginate: 5
author:
    name: azq
    github: POST-AND-GET
    email:
    gitcafe: anzhiqing
    twitter:
    facebook:
    googleplus:
    weibo: azqwill
atom_path: /atom.xml
rss_path: /rss.xml

# Build settings
markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]
permalink: /:categories/:year-:month/:title.html

assets_path: /assets
sass:
    sass_dir: assets/_sass
    style: :compressed

# comment
comments:
    duoshuo:
        name:post-and-get
        rcomments:
            num: 10
            avatar: 0
            time: 0
            title: 0
            admin: 0
            length: 26
# 网站统计
analytics:
    baidu:
        siteid:46bd585da3316b294a1bafac920786ce

