title: "azq.space"
url: "//azq.space"
highlighter: pygments
paginate: 5
author:
    name: azq
    github: POST-AND-GET
    email:
    gitcafe: anzhiqing
    twitter:
    facebook:
    googleplus:
    weibo: azqwill
atom_path: /atom.xml
rss_path: /rss.xml

markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]
permalink: /:categories/:year-:month/:title.html

assets_path: /assets
sass:
    sass_dir: assets/_sass
    style: :compressed

comments:
    duoshuo:
        name: post-and-get
        rcomments:
            num: 10
            avatar: 0
            time: 0
            title: 0
            admin: 0
            length: 26
analytics:
    baidu:
        siteid: 2f842a6d2280c26b5d7bc63d6cb4374e

