var data = [
	{
		"id":"0",
		"name":"超级英雄",
		"icon":"images/source/chaojiyingxiong/icon.jpg",
		"img":[
		"images/source/chaojiyingxiong/1.jpg",
		"images/source/chaojiyingxiong/2.jpg",
		"images/source/chaojiyingxiong/3.jpg",
		"images/source/chaojiyingxiong/4.jpg",
		"images/source/chaojiyingxiong/5.jpg"
		],
		"recommend":"images/source/chaojiyingxiong/r.jpg",
		"downloadurl":["http://download.adwo.com/201501/P14468A.apk","###"],
		"downloadimg":["images/source/chaojiyingxiong/download.png",""],
		"type":"卡牌",
		"size":"121.51MB",
		"operators":"安沃游戏",
		"support":"Android",
		"version":"1.4.7",
		"text":"《超级英雄》是国内首款冒险卡牌手游，聚集了全球最热门的英雄大胆创新，融合了回合制的战斗机制，完美还原英雄们的成名技能！各种英雄技能超炫华丽，超酷的视觉冲击及打击感精致入微!回忆儿时的英雄梦，你最想成为哪个英雄？在《超级英雄》里将实现你的梦想！选择你最喜欢的英雄，拯救世界！GO，让我们一起出发！ 钢铁侠、美国队长、绿巨人、蝙蝠侠、绿箭侠、超级赛亚人......全宇宙最热门的超级英雄，正在集结！为了捍卫世界和平，在这里他们将成为你的队友，和超级英雄们一起并肩作战！为了梦想！为了世界和平！英雄们，热血战斗吧！"
		
	},{
		"id":"1",
		"name":"放开那三国",
		"icon":"images/source/fangkainasanguo/icon.png",
		"img":[
		"images/source/fangkainasanguo/1.jpg",
		"images/source/fangkainasanguo/2.jpg",
		"images/source/fangkainasanguo/3.jpg",
		"images/source/fangkainasanguo/4.jpg"
		],
		"recommend":"images/source/fangkainasanguo/r.jpg",
		"downloadurl":["http://download.adwo.com/201501/fknsg_zyx_4.2.4_anao_1412171514.apk","###"],
		"downloadimg":["images/source/fangkainasanguo/download.png",""],
		"type":"卡牌",
		"size":"103.24MB",
		"operators":"安沃游戏",
		"support":"Android",
		"version":"4.2.4",
		"text":"2014超萌Q版卡牌手游——《放开那三国》一周年请点正式启动！新老玩家福利全面升级！七大谜题活动豪送百万礼金，回馈力度前所未见!自App上架以来，蝉联畅销版前十，创造三国题材卡牌手游领先地位。《放开那三国》——放不开的手机游戏！快乐，从此触手可及!1.超萌Q版画风，怪蜀黍、小正太、软妹子轮番登场，让你大呼过瘾！2.完善卡牌收集系统，三国群英一网打尽，绝色后宫随你组建！3.超高紫卡爆率，贴心的入门教学。新手一秒变大神，菜鸟瞬间成高玩！4.独创怒气系统，极致的战斗体验，让你的武将爆框再爆框！5.道具全产出，所有游戏道具均可在游戏内产出，减少玩家差距，增大游戏乐趣！"
		
	},{
		"id":"2",
		"name":"攻城掠地",
		"icon":"images/source/gongchengluedi/icon.png",
		"img":[
		"images/source/gongchengluedi/1.jpg",
		"images/source/gongchengluedi/2.jpg",
		"images/source/gongchengluedi/3.jpg",
		"images/source/gongchengluedi/4.jpg",
		"images/source/gongchengluedi/5.jpg"
		],
		"recommend":"images/source/gongchengluedi/r.png",
		"downloadurl":["http://download.adwo.com/201501/100132_20141224165257_300426.apk","###"],
		"downloadimg":["images/source/gongchengluedi/download.png",""],
		"type":"SLG",
		"size":"65.41MB",
		"operators":"安沃游戏",
		"support":"Android",
		"version":"2.1.5",
		"text":"和好基友建功立业的时刻来到了，推倒周瑜霸占吕布，让貂蝉小乔哭去吧。官职王位统统竞争上岗，谁的拳头大谁就是国王，让公务员文考成为过去。和国籍受限Say拜拜，折冲将军甘宁跳槽去蜀国，吴国挖角野性女王祝融。吴国城墙比我高，打！蜀国美女比我多，打！24小时的国战群架想打就打。文治武功做一代三国名将，屯粮草，升科技，建功勋，打造最强铁血兵团。万万没想到，自从玩《攻城掠地》后，妈妈再也不担心历史成绩不及格了。"
		
	},{
		"id":"3",
		"name":"三国杀传奇",
		"icon":"images/source/sanguoshachuanqi/icon.png",
		"img":[
		"images/source/sanguoshachuanqi/1.jpg",
		"images/source/sanguoshachuanqi/2.jpg",
		"images/source/sanguoshachuanqi/3.jpg",
		"images/source/sanguoshachuanqi/4.jpg",
		"images/source/sanguoshachuanqi/5.jpg"
		],
		"recommend":"images/source/sanguoshachuanqi/r.jpg",
		"downloadurl":["http://download.adwo.com/201501/20004_140021_8.7.13.10_303_alipay_bfSdk.apk","###"],
		"downloadimg":["images/source/sanguoshachuanqi/download.png",""],
		"type":"卡牌",
		"size":"93.12 MB",
		"operators":"安沃游戏",
		"support":"Android",
		"version":"8.7.13.10",
		"text":"剧情闯关系统因无需玩家控制的原因采用回合制战斗，目前最多以7V7的形式出阵对战，战斗技能在三国杀原有的基础上彰显出深入人心的画面特效，技能绚丽打击感超强，并且游戏内武将由三国杀原班人马配音，视觉与听觉上的盛宴！每一个关卡都有不同的星数级别哦，玩家们通过集满一定的星数可以开启关卡中的宝箱获得宝箱内的奖励，说不定还有惊人道具呢~"
		
	},{
		"id":"4",
		"name":"血族",
		"icon":"images/source/xuezu/icon.png",
		"img":[
		"images/source/xuezu/1.jpg",
		"images/source/xuezu/2.jpg",
		"images/source/xuezu/3.jpg",
		"images/source/xuezu/4.jpg",
		"images/source/xuezu/5.jpg"
		],
		"recommend":"images/source/xuezu/r.jpg",
		"downloadurl":['http://download.adwo.com/201501/XZ_1.450_201411281749_GG1226.apk','###'],
		"downloadimg":["images/source/xuezu/download.png",""],
		"type":"卡牌",
		"size":"128.11MB",
		"operators":"安沃游戏",
		"support":"Android",
		"version":"1.16",
		"text":"2014首款吸血鬼卡牌RPG大作《血族》，根据超人气同名漫画改编。由盛大游戏旗下王牌团队传世工作室精心打造，并力邀华人顶级漫画大师，《十万个冷笑话》全明星声优阵容加盟！游戏打破传统卡牌手游无脑对战模式，通过策略布阵，手势操控经典像素角色，展现超华丽战斗特效和超激爽打击感！这一次，让指尖引领超乎想象的“声动”战斗体验！ 【人气漫画改编 明星声优加盟】 超人气同名漫画改编，华人顶级漫画大师加盟研发！《十万个冷笑话》全明星阵容上演“声优大戏”，不容错过的“生动”卡牌手游大作！ 【300+激萌角色 超炫战斗阵容】 300+激萌卡牌设定，3D动态卡面展示，搭配经典像素化角色和独一无二的华丽打击特效，超炫战斗阵容由你打造！ 【全手势操作 超绝动画战斗】 全手势爽快操作，滑屏释放超必杀技，防御、合击、队长技超高端策略组合，卡牌玩得不只是对撞！ 【特色养成系统 纯正RPG玩法】 6大属性、5大职业、10个二转职业，超过60件装备及300种不同技能及成长式领地系统，纯正RPG玩法，超耐玩卡牌手游精品之作！ 【爵位争夺 超激烈竞技PK】 独有吸血鬼爵位系统，PVP竞技争霸，异次元大战即将打响！"
		
	},{
		"id":"5",
		"name":"英雄之剑",
		"icon":"images/source/yingxiongzhijian/icon.png",
		"img":[
		"images/source/yingxiongzhijian/1.jpg",
		"images/source/yingxiongzhijian/2.jpg",
		"images/source/yingxiongzhijian/3.jpg",
		"images/source/yingxiongzhijian/4.jpg"
		],
		"recommend":"images/source/yingxiongzhijian/r.jpg",
		"downloadurl":["http://download.adwo.com/201501/6000000765.apk","###"],
		"downloadimg":["images/source/yingxiongzhijian/download.png",""],
		"type":"横版RPG",
		"size":"53.52 MB",
		"operators":"安沃游戏",
		"support":"Android",
		"version":"1.0",
		"text":"“以你之名，铸英雄之剑”！<br>2014全民格斗手游《英雄之剑》震撼来袭！浮空连击秒杀全场，体感战斗畅爽享受。虚拟摇杆随心操纵，高清画质极致体验。百套外装绚丽变身，穿出时尚彰显个性。公平交易人人平等，自由买卖欢笑开怀。<br>60M超小安装包，随时随地想下就下！<br>物品交易全面开放，人人平等绝对公平！<br>50套外装随你搭配，尽显时尚张扬本色！<br>觉醒技能无消耗释放，全屏秒杀炫爆战场！<br>200+多样副本，虐杀BOSS征服大陆！<br>1080P高清画面，精致美感指尖展现！"
		
	},{
		"id":"6",
		"name":"乱斗西游",
		"icon":"images/source/luandouxiyou/icon.png",
		"img":[
		"images/source/luandouxiyou/1.jpg",
		"images/source/luandouxiyou/2.jpg",
		"images/source/luandouxiyou/3.jpg",
		"images/source/luandouxiyou/4.jpg",
		"images/source/luandouxiyou/5.jpg"
		],
		"recommend":"",
		"downloadurl":['http://download.adwo.com/201501/ldxy_netease_adwo_cps_1.0.4.apk','###'],
		"downloadimg":["images/source/luandouxiyou/download.png",""],
		"type":"ARPG",
		"size":"154.84MB",
		"operators":"安沃游戏",
		"support":"Android",
		"version":"1.0.0",
		"text":"掌上DOTA！颠覆性动作手游《乱斗西游》2014最具颠覆性动作手游《乱斗西游》来啦！真正的颠覆性战斗，告别无脑数值碾压，凭实力和操作踏上人生巅峰！独创DOTA式真人对抗，让你随时随地畅享掌上DOTA的痛快体验！颠覆性画面表现，快节奏爽快连击，带给你最痛快淋漓的动作快感！超过30位个性英雄，上百种强力技能，让每一局游戏都充满新鲜！快来统率西游群豪，踏上全新取经之旅吧！"
		
	},{
		"id":"7",
		"name":"天龙八部3D",
		"icon":"images/source/tianlongbabu/icon.png",
		"img":[
		"images/source/tianlongbabu/1.jpg",
		"images/source/tianlongbabu/2.jpg",
		"images/source/tianlongbabu/3.jpg",
		"images/source/tianlongbabu/4.jpg",
		"images/source/tianlongbabu/5.jpg"
		],
		"recommend":"",
		"downloadurl":['http://download.adwo.com/201502/CPS_AnWo_TLBB3D_1_98_0_0_2015_01_17_0151.apk','###'],
		"downloadimg":["images/source/tianlongbabu/download.png",""],
		"type":"横版RPG",
		"size":"154M",
		"operators":"安沃游戏",
		"support":"Android",
		"version":"1.98.0",
		"text":"《天龙八部3D》是由畅游自主研发，中国第一武侠网游《天龙八部》原班人马倾力打造的首款3D武侠MMORPG手游巨作。游戏改编自金庸经典巨作《天龙八部》，以U3D引擎打造的极致炫丽画面，全3D唯美水墨武侠风格，游戏和真实江湖完美融合，带你领略刀光剑影的江湖世界。四大门派激情共武，身临其境般的极致战斗体验。十余种稀有珍兽伙伴，数百名侠客养成，绝色美人佳丽伴你闯荡五湖四海，持强扶弱。婚姻、帮会、自助交易平台等特色交互式玩法系统让快意恩仇的江湖故事再掀帮派纷争。"
		
	},{
		"id":"8",
		"name":"西游神魔决",
		"icon":"images/source/xiyoushenmo/icon.png",
		"img":[
		"images/source/xiyoushenmo/1.jpg",
		"images/source/xiyoushenmo/2.jpg",
		"images/source/xiyoushenmo/3.jpg",
		"images/source/xiyoushenmo/4.jpg",
		"images/source/xiyoushenmo/5.jpg"
		],
		"recommend":"",
		"downloadurl":['http://download.adwo.com/201502/sm_netease_adwo_cps_dev_1.6.1.apk ','###'],
		"downloadimg":["images/source/xiyoushenmo/download.png",""],
		"type":"横版RPG",
		"size":"138M",
		"operators":"安沃游戏",
		"support":"Android",
		"version":"1.6.1",
		"text":"手游版大话西游3，史诗公测！2014，网易首款2D回合制手游大作——《西游神魔决》，震撼来袭！网易大话西游3开发组，耗资千万，再现经典，网易回合，世界品质！秉承网易经典回合精髓，《西游神魔决》独创紧张刺激的符印擂台玩法，打造2D回合制手游巅峰体验。原汁原味的回合大作，美轮美奂的国风画面，刀剑无情的符印擂台，血染沙场的屠城之战，危机四伏的三界之争，波澜壮阔的西游史诗，成就2D回合制手游的全新标杆！"
		
	}

];
